version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '8080:8080'
    environment:
       MYSQL_DATABASE: 'xmeme'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'hideandseek'
       MYSQL_ROOT_PASSWORD: 'hideandseek'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db